export default {
  HALCYON_WIZARD_CREATE            : 'HALCYON_WIZARD_CREATE',
  HALCYON_WIZARD_DESTROY           : 'HALCYON_WIZARD_DESTROY',
  HALCYON_WIZARD_NAVIGATE_TO_INDEX : 'HALCYON_WIZARD_NAVIGATE_TO_INDEX',
  HALCYON_WIZARD_SUBMIT_START      : 'HALCYON_WIZARD_SUBMIT_START',
  HALCYON_WIZARD_SUBMIT_END        : 'HALCYON_WIZARD_SUBMIT_END'
};
