export default {
  EXAMPLE_MODEL_RESET           : 'EXAMPLE_MODEL_RESET',
  EXAMPLE_MODEL_UPDATE_PROPERTY : 'EXAMPLE_MODEL_UPDATE_PROPERTY',
  EXAMPLE_MODEL_UPDATE_LEAF     : 'EXAMPLE_MODEL_UPDATE_LEAF'
};
