export const HALCYON_WIZARD_CREATE      = 'HALCYON_WIZARD_CREATE';
export const HALCYON_WIZARD_DESTROY     = 'HALCYON_WIZARD_DESTROY';
export const HALCYON_WIZARD_SET_MODEL   = 'HALCYON_WIZARD_SET_MODEL';
export const HALCYON_WIZARD_STEP_CHANGE = 'HALCYON_WIZARD_STEP_CHANGE';
export const HALCYON_WIZARD_OPEN_INDEX  = 'HALCYON_WIZARD_OPEN_INDEX';
