export const HALCYON_WIZARD_CREATE      = 'HALCYON_WIZARD_CREATE';
export const HALCYON_WIZARD_DESTROY     = 'HALCYON_WIZARD_DESTROY';
export const HALCYON_WIZARD_STEP_CHANGE = 'HALCYON_WIZARD_STEP_CHANGE';
